// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNUlfgohEvW7duc5fME5p74eaQVWsC84Q',
    appId: '1:217583587517:web:4f2447f8c13a9782c667d4',
    messagingSenderId: '217583587517',
    projectId: 'flutter-chat-app-b8219',
    authDomain: 'flutter-chat-app-b8219.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b8219.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPCWGYAtA9MI13SDDVcgiRDiT6tM4WlE',
    appId: '1:217583587517:android:069433d16022d289c667d4',
    messagingSenderId: '217583587517',
    projectId: 'flutter-chat-app-b8219',
    storageBucket: 'flutter-chat-app-b8219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB88FZ1f7G8EYzbJ_Ok9WXsvpM8wAKKn0',
    appId: '1:217583587517:ios:d2e272bfd104a9f5c667d4',
    messagingSenderId: '217583587517',
    projectId: 'flutter-chat-app-b8219',
    storageBucket: 'flutter-chat-app-b8219.appspot.com',
    iosBundleId: 'com.example.udemyappfirst',
  );
}
